<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function getQueryOrderedByCreatedAt()
    {
         $dql = "SELECT post FROM AppBundle:Post post ORDER BY post.createdAt DESC";
        return $this->getEntityManager()->createQuery($dql);
    }
    
    public function getAllPublished()
    {
        $query = $this->createQueryBuilder('p') 
                    ->leftJoin('p.user', 'u')
                    ->orderBy('p.createdAt', 'DESC')
                    ->getQuery();
        
        return $query;
    }
    
    public function getAllNotPublished()
    {
        $query = $this->createQueryBuilder('p')
                    ->update()
                    ->set('p.status',1)
                    ->where('p.status = 3')
                    ->andWhere('p.publish < :datenow')
                    ->setParameter('datenow', new \DateTime('now'))
                    ->getQuery();
        $results = $query->execute();
        
        return $results;
    }
    
        
}
